---
- hosts: all
  vars_files:
    - vars.yml
  sudo: yes
  tasks:
  - name: make doc osmium
    command: "make doc chdir=/srv/osmium/"
  - name: make install osmium
    command: "make install chdir=/srv/osmium/"
  - name: make osm-history-splitter
    command: "make chdir=/srv/osm-history-splitter/" 

- hosts: all
  sudo_user: postgres
  sudo: yes
  gather_facts: no

  tasks:
  - name: create database
    postgresql_db: name=vagrant
  - name: create vagrant postgres user
    postgresql_user: db=vagrant name=vagrant password=vagrant priv=ALL role_attr_flags=CREATEDB,CREATEUSER
  



